### PR TITLE
Sphinx actions

### PR DESCRIPTION
**Pull request by turian**
This adds github actions for sphinx build and sphinx link check. I also found one broken link.

This isn't perfect because it gets warnings like this:

```
WARNING: autodoc: failed to import class 'pretrain_dataloader.NCropAugmentation' from module 'solo.utils'; the following exception was raised:
No module named 'solo.utils.pretrain_dataloader'
```

I think this is because of whether the pip install actually creates the right module names.

### CODE REVIEW

**Comment by vturrisi** [comment]
Hi @turian thanks for contributing. Just so I get it, this will simply check if sphinx is building correctly?

**Comment by vturrisi** [comment]
I've also just checked and this error is because we changed the structure of the library but did not update the docs. I'll try to address this next week.

**Comment by turian** [comment]
> Hi @turian thanks for contributing. Just so I get it, this will simply check if sphinx is building correctly?

Correct, and also that no links are broken. This is useful for when you start publishing docs on rtfd

**Comment by vturrisi** [comment]
I see @turian. Gonna check the commit later today/tomorrow and also use your PR to fix the issues that we have with the current documentation.

**Comment by turian** [comment]
@vturrisi Great. I'm excited to work with sololearn but without built docs its hard to know where to start.

In particular, I want to start using solo-learn for non-vision data, using different backbones, and port from my existing vicreg implementation.

**Comment by vturrisi** [comment]
@turian yes, indeed one thing that's not solidified is our documentation. Hopefully we will get around it in the next months.

**Review by DonkeyShot21 — APPROVED** [review]

**Pull request merged**
