### PR TITLE
Add All4One

### PR DESCRIPTION
**Pull request by ImaGonEs**
…tional enconding utils added. README file adapted to include All4One.

### CODE REVIEW

**Comment by vturrisi** [comment]
hey @ImaGonEs thanks for contributing. We are just missing some things that need to be added before merging. Can you add the tests and documentation? You can copy-paste them from the available methods and change them accordingly. Another thing, I noticed that the config file for imagenet-100 is missing.

**Comment by ImaGonEs** [comment]
Hi!

Tests and documentation added (I adapted the ones you created for NNCLR/NNBYOL). ImageNet100 config file is now available also.

Tell me if anything is missing :)

**Comment by vturrisi** [comment]
@ImaGonEs thanks for that. I took a quick look, but I'll read it more carefully later. One thing is to move the documentation of the positional_encodings to `solo/utils.rst` instead of having a separate file for it.

**Comment by ImaGonEs** [comment]
Sure. I moved it to utils.rst and added the temperature parameter to the test (I missed it on the last commit).

**Comment by vturrisi** [comment]
@ImaGonEs I've fixed some minor stuff on the code that was out of standard. I'll merge the code, if there's anything else, let me know.

**Comment by ImaGonEs** [comment]
Thank you for the effort! I did the code using an older version, sorry for the inconvenience. 
Now that I checked it, the single thing I miss is a note in the news section (I forgot to add it in my commits). Should I add it? :)

**Comment by vturrisi** [comment]
@ImaGonEs I'll add it :)

**Pull request merged**
