### PR TITLE
bump PL dependencies

### PR DESCRIPTION
**Pull request by Borda**
setting some more recent dependencies
see tests in https://github.com/Lightning-AI/ecosystem-ci/pull/82

### CODE REVIEW

**Comment by Borda** [comment]
@vturrisi could you pls approve running your CI? :otter:

**Comment by Borda** [comment]
seem that the same failing tests are coming from master as I see being fixed in #312

**Comment by vturrisi** [comment]
Yes, the builder has some issues which I still haven't had the time to solve. I'll likely disable it for the time being sometime today. Then I can commit and pull the fixes here.

**Comment by vturrisi** [comment]
@Borda merged this with #312.

**Pull request closed without merging**
